site_name: timberas

theme:
  name: readthedocs
  navigation_depth: 4

plugins:
  - search 
  - mkdocstrings:
      handlers:
        python:
            setup_commands:
                - import sys
                - sys.path.append('../')
            options:
              show_submodules: false
              separate_signature: true
              show_category_heading: true
              group_by_category: true
              show_source: false
              show_root_heading: false
              show_root_toc_entry: false
              heading_level: 3
              filters: ['!main']
              members_order: source
            paths: [src]


nav:
  - Introduction:
    - About: index.md
    - Installation: install.md
  - Tutorials: 
    - Getting Started I: tutorial-1.md
    - Getting Started II: tutorial-2.md
  - Technical:
    - API Reference: reference.md

watch:
  - src/timberas