site_name: My Docs

theme:
  name: readthedocs
  navigation_depth: 4

plugins:
  - search 
  - mkdocstrings:
      handlers:
        python:
            setup_commands:
                - import sys
                - sys.path.append('../')
            options:
              show_submodules: false
              separate_signature: true
              show_category_heading: true
              group_by_category: true
              show_source: false
              show_root_heading: false
              show_root_toc_entry: false
              heading_level: 3
              filters: ['!main']
              members_order: source


nav:
  - timberas docs: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - API: reference.md
  - explanation.md

watch:
  - src/timberas